# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
language: python
sudo: required
dist: xenial
python: "3.7"

install:
  - pip install pytest-cov
  - pip install .

script:
  - cd tests
  - py.test --cov=benten

after_success:
  - coveralls